repos:
  - repo: local
    hooks:
      - id: black-check
        name: Check code formatting with black
        entry: black --check .
        language: system
        pass_filenames: false
      - id: ruff
        name: Run ruff
        entry: ruff check .
        language: system
        pass_filenames: false
